

# colunas do data frame
CODE_ESTADO = "CODE_ESTADO"
NOME_ESTADO = "NOME_ESTADO"

CODE_REGIAO_INTERMEDIARIA = "CODE_REGIAO_INTERMEDIARIA"
NOME_REGIAO_INTERMEDIARIA = "NOME_REGIAO_INTERMEDIARIA"

CODE_REGIAO_IMEDIATA = "CODE_REGIAO_IMEDIATA"
NOME_REGIAO_IMEDIATA = "NOME_REGIAO_IMEDIATA"

CODE_CIDADE = "CODE_CIDADE"
CODE_CIDADE_COMPLETO = "CODE_CIDADE_COMPLETO"
NOME_CIDADE = "NOME_CIDADE"
NOME_CIDADE_NORMALIZADO = "NOME_CIDADE_NORMALIZADO"

CODE_BAIRRO = "CODE_BAIRRO"
CODE_BAIRRO_COMPLETO = "CODE_BAIRRO_COMPLETO"
NOME_BAIRRO = "NOME_BAIRRO"

# colunas das coordenadas
CENTROIDE   = "centroide"
LATITUDE    = "LATITUDE"
LONGITUDE   = "LONGITUDE"
CD_MUN      = "CD_MUN"


# colunas em ordem
COLUNAS_PADRAO = [
    CODE_ESTADO,
    NOME_ESTADO,

    CODE_REGIAO_INTERMEDIARIA,
    NOME_REGIAO_INTERMEDIARIA,

    CODE_REGIAO_IMEDIATA,
    NOME_REGIAO_IMEDIATA,

    CODE_CIDADE,
    CODE_CIDADE_COMPLETO,
    NOME_CIDADE,

    CODE_BAIRRO,
    CODE_BAIRRO_COMPLETO,
    NOME_BAIRRO,
]

LEN_CODE_UF = 2
LEN_CODE_REGIAO_INTERMEDIARIA = 4
LEN_CODE_REGIAO_IMEDIATA = 6
LEN_CODE_MUNICIPIO = 5
LEN_CODE_MUNICIPIO_COMPLETO = 7
LEN_CODE_BAIRRO = 2
LEN_CODE_BAIRRO_COMPLETO = 9


TIPOS_COLUNAS = {
    CODE_ESTADO: "Int64",
    NOME_ESTADO: str,

    CODE_REGIAO_INTERMEDIARIA: "Int64",
    NOME_REGIAO_INTERMEDIARIA: str,

    CODE_REGIAO_IMEDIATA: "Int64",
    NOME_REGIAO_IMEDIATA: str,

    # tem que ser str pq ele tem codigos que começam com zero?
    CODE_CIDADE: str,
    CODE_CIDADE_COMPLETO: "Int64",
    NOME_CIDADE: str,

    CODE_BAIRRO: "Int64",
    CODE_BAIRRO_COMPLETO: "Int64",
    NOME_BAIRRO: str
}

