

# colunas do data frame
CODE_UF = "CODE_UF"
NOME_UF = "NOME_UF"

CODE_REGIAO_INTERMEDIARIA = "CODE_REGIAO_INTERMEDIARIA"
NOME_REGIAO_INTERMEDIARIA = "NOME_REGIAO_INTERMEDIARIA"

CODE_REGIAO_IMEDIATA = "CODE_REGIAO_IMEDIATA"
NOME_REGIAO_IMEDIATA = "NOME_REGIAO_IMEDIATA"

CODE_MUNICIPIO = "CODE_MUNICIPIO"
CODE_MUNICIPIO_COMPLETO = "CODE_MUNICIPIO_COMPLETO"
NOME_MUNICIPIO = "NOME_MUNICIPIO"

CODE_DISTRITO = "CODE_DISTRITO"
CODE_DISTRITO_COMPLETO = "CODE_DISTRITO_COMPLETO"
NOME_DISTRITO = "NOME_DISTRITO"

# colunas em ordem
COLUNAS_PADRAO = [
    CODE_UF,
    NOME_UF,

    CODE_REGIAO_INTERMEDIARIA,
    NOME_REGIAO_INTERMEDIARIA,

    CODE_REGIAO_IMEDIATA,
    NOME_REGIAO_IMEDIATA,

    CODE_MUNICIPIO,
    CODE_MUNICIPIO_COMPLETO,
    NOME_MUNICIPIO,

    CODE_DISTRITO,
    CODE_DISTRITO_COMPLETO,
    NOME_DISTRITO,
]

LEN_CODE_UF = 2
LEN_CODE_REGIAO_INTERMEDIARIA = 4
LEN_CODE_REGIAO_IMEDIATA = 6
LEN_CODE_MUNICIPIO = 5
LEN_CODE_MUNICIPIO_COMPLETO = 7
LEN_CODE_DISTRITO = 2
LEN_CODE_DISTRITO_COMPLETO = 9


TIPOS_COLUNAS = {
    CODE_UF: "Int64",
    NOME_UF: str,

    CODE_REGIAO_INTERMEDIARIA: "Int64",
    NOME_REGIAO_INTERMEDIARIA: str,

    CODE_REGIAO_IMEDIATA: "Int64",
    NOME_REGIAO_IMEDIATA: str,

    CODE_MUNICIPIO: "Int64",
    CODE_MUNICIPIO_COMPLETO: "Int64",
    NOME_MUNICIPIO: str,

    CODE_DISTRITO: "Int64",
    CODE_DISTRITO_COMPLETO: "Int64",
    NOME_DISTRITO: str
}

